### ISSUE TITLE
v2 requires go.mod to be adjusted and for the repo to be re-tagged at v2.0.0

### ISSUE THREAD

**Issue by bnfinet** [evanoberholster/timezoneLookup#7]
Thanks for all the fine work on this lib.  I'm very interested in using `v2` but unfortunately I'm unable to import it in its current form.  I think these instructions would be of help...

https://therootcompany.com/blog/bump-go-package-to-v2/

After `go.mod` is adjusted you'll need to reset the `v2.0.0` tag.  IIRC in order to delete a remote tag on github you'll need to run `git push origin :v2.0.0`

**Comment by evanoberholster** [comment]
@bnfinet This has been resolved by @gaker. Closing Issue
